### PR TITLE
Adding GitHub CI

### PR DESCRIPTION
**Pull request by JRPan**
One is failing. Not my CI's problem. 
```
GPGPU-Sim ** ERROR: Unknown Option: '-gpuwattch_xml_file'
```

### CODE REVIEW

**Comment by William-An** [comment]
There are lots of git error messages complaining about `dubious ownership`, possibly due to cloning `accel-sim`? Could you try to suppress them? Here are some links that might help:
- https://github.com/actions/checkout/issues/1048
- https://community.atlassian.com/t5/Bitbucket-questions/Getting-code-128-fatal-detected-dubious-ownership-in-repository/qaq-p/2373506#:~:text=This%20error%20is%20returned%20when,own%20clone%20of%20the%20repository.

**Comment by William-An** [comment]
The `-gpuwattch_xml_file` error is cased by GTX480's `gpgpusim.config` still has `-gpuwattch_xml_file` while that has been updated to `-accelwattch_xml_file` in [`gpu-sim.cc`](https://github.com/accel-sim/gpgpu-sim_distribution/blob/9aeacdf656bcee6ddac9d8f9c4269a07bb64a255/src/gpgpu-sim/gpu-sim.cc#L102-L104), which defaults to `accelwattch_sass_sim.xml`.

**Comment by William-An** [comment]
The [change](https://github.com/VijayKandiah/gpgpu-sim_distribution/tree/84c6cf45131e42b1a724ebf7977987a9ddb70db9) to `-accelwattch_xml_file` was done before jenkins I believed with travis also down. I guess it was never caught that the GTX480 config cannot run with current gpgpusim.

**Comment by JRPan** [comment]
> There are lots of git error messages complaining about `dubious ownership`, possibly due to cloning `accel-sim`? Could you try to suppress them? Here are some links that might help:
> 
> * [fatal: detected dubious ownership in repository at actions/checkout#1048](https://github.com/actions/checkout/issues/1048)
> * https://community.atlassian.com/t5/Bitbucket-questions/Getting-code-128-fatal-detected-dubious-ownership-in-repository/qaq-p/2373506#:~:text=This%20error%20is%20returned%20when,own%20clone%20of%20the%20repository.

- Fixed

**Review by William-An — APPROVED** [review]

**Pull request merged**
