### PR TITLE
Ported aerialvision to use python3 instead of python2

### PR DESCRIPTION
**Pull request by christindbose**
Modified all files of aerialvision to use python3. Mostly formatting changes.

### CODE REVIEW

**Comment by cesar-avalos3** [comment]
Can you exclude the binary files in the cache?

**Comment by christindbose** [comment]
Done.

**Comment by cesar-avalos3** [comment]
Is bin/aerialvision.py still the entry point? If so, it also needs to be updated

**Comment by christindbose** [comment]
My bad. Updated it as well in this commit.

**Comment by cesar-avalos3** [comment]
Works perfectly fine, approved

**Review by cesar-avalos3 — APPROVED** [review]

**Pull request merged**
